version:'3'
services:
        dbimage:
        container_name:devopsdb
        build:./Docker-db
        ports:'3303:3306'

        app:
        container_name:devopsapp
        build: ./docker-app
        ports:'7777:8080'
